# Message related constants
MAX_USERNAME_LENGTH = 30
WEBSOCKET_PING_INTERVAL = 30  # seconds 

# User related constants
MIN_USERNAME_LENGTH = 3
MAX_DISPLAY_NAME_LENGTH = 50

# Channel related constants
MIN_CHANNEL_NAME_LENGTH = 3
MAX_CHANNEL_NAME_LENGTH = 50
MAX_CHANNEL_DESCRIPTION_LENGTH = 200 